/**
 * Sidebar config for the Engineering Playbook.
 * Autogenerated from the folder structure in /docs-playbook.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  playbookSidebar: [
    {
      type: "autogenerated",
      dirName: ".", // generate from the root of docs-playbook
    },
  ],
};

export default sidebars;
